### ISSUE TITLE
New release with the changes made in hotdoc 0.16

### ISSUE THREAD

**Issue by vitoyucepi** [hotdoc/hotdoc_lumen_theme#4]
## Summary

I'm not sure if I found the repository correctly, but I'm trying to help fix the problem in the gstreamer documentation associated with the React Dev Tools.

Could you tag and release a new version of the theme because it's used by gstremear to generate the hotdoc documentation site.

## Details

Using React Dev Tools with the hotdoc sites causes some scrolling issues. I think gstreamer is using this repository to generate the documentation, because I've noticed that in the build script available at https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/afa41ec3bc7782cc7db0d9b0e971cbfba3bc515e/subprojects/gst-docs/meson.build#L104.
```meson
html_theme = 'https://github.com/hotdoc/hotdoc_lumen_theme/releases/download/0.15/hotdoc_lumen_theme-0.15.tar.xz?sha256=1ea7fd00d8dfd607d175c59e2d89918a55114c867f697a94c703f314b0d9b4b6'
```

The scrolling problem was fixed in the hotdoc itself some time ago in version *0.16*. To complete the fix, I think it's necessary to do a release for the theme as well.

## References
React Dev Tools issue: https://github.com/facebook/react/issues/27578
Hotdoc issue: https://github.com/hotdoc/hotdoc/issues/271
Gstreamer issue: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3070

**Comment by thiblahute** [comment]
Done: https://github.com/hotdoc/hotdoc_lumen_theme/releases/tag/0.16
